os: linux
dist: focal
arch: arm64-graviton2
group: dev
jobs:
  include:
    - language: ruby
      rvm:
        - 2.6.3
      script:
        - ruby hello.rb
    - language: cpp
      compiler: gcc
      script:
        - g++ hello.cpp -o travis_gcc_cpp98
        - ./travis_gcc_cpp98
        
    - language: cpp
      compiler: clang
      script:
        - clang++ hello.cpp -o travis_gcc_cpp98
        - ./travis_gcc_cpp98

