matrix:
    os: linux
    dist: focal
    arch: arm64-graviton2
    group: dev
    
    include:
        - language:
          rvm:
            - 2.5
          script:
            - ruby hello.rb
        
        - language:
          compiler: clang
          script:
            - g++ hello.cpp          
